# Solace router and access info for sample team
# The --env CLI parameter selects which environment to target.

---
inventory:
    hosts:
    # name matches the --env value used on the command line
    - name: "dev"
      host: "localhost"
      sempUrl: "http://localhost:8080"
      sempUser: "admin"
      vpn: "default"

    - name: "uat"
      host: "localhost"
      sempUrl: "http://localhost:8080"
      sempUser: "admin"
      vpn: "default"
