---
# Input file for solace config management script
# this file name (input/default.yaml) is hardcoded and this is the only file script will look for.

# Router URL and credentials
router:
   label: "nram-dev1-solace-cloud"  #  used for dir name and logging purposes
   sempUrl: "https://mr-connection-xoqmdwtfgbe.messaging.solace.cloud:943"
   sempUser: "nram-dev1-admin"
   sempPassword: "secret"
   vpn: "nram-dev1"


# Run parameters
run_params:
   # logging
   verbose: false
   # Action to perform
   action: 
        # valid values: create, update, none
        # valid entries: queues, subscriptions, client-username, client-profile, acl-profile
        queues: "create"
        subscriptions: "create"
        client-usernames: "create"
        client-profiles: "create"
        acl-profiles: "create"


# User inputs
# list of queues and topic subscriptions to create
queues:
   - queue: Test/Git/Sample/NoSubs
   - queue: Test/Git/Sample/WithSubs
     subscriptions:
        - test/topic/1
        - test/topic/*


# Template values for creating Queues
templates:
   # Queue template to use for creating queues.
   # These values can be overwritten in the input CSV file
   # Any property not listed here / input CSV will use Solace defaults
   queue:
      accessType: "non-exclusive"
      deadMsgQueue: "#DEAD_MSG_QUEUE"
      maxBindCount: 10
      maxDeliveredUnackedMsgsPerFlow: 1000
      maxMsgSize: 1000000
      maxMsgSpoolUsage: 1234
      maxRedeliveryCount: 2
      maxTtl: 0
      owner: "solace-cloud-client"
      permission: "no-access"
      redeliveryEnabled: true
      respectTtlEnabled: true
      # subscriptionTopic: ""
   dmqueue:
      accessType: "exclusive"
      deadMsgQueue: "#DEAD_MSG_QUEUE"
      maxBindCount: 1
      maxDeliveredUnackedMsgsPerFlow: 1000
      maxMsgSize: 1000000
      maxMsgSpoolUsage: 5000
      maxRedeliveryCount: 0
      maxTtl: 0
      owner: "solace-cloud-client"
      permission: "no-access"
      redeliveryEnabled: false
      respectTtlEnabled: false
      subscriptionTopic: ""

system:
   configFile: "config/system.yaml"
