# Sample inventory file for the Solace Cloud environment
# Solace router and access info for the application
# sempPassword is read from the environment variable
# In GitHub Actions, set SEMP_PASSWORD in Secrets/Action/Secrets  

---
inventory:
    # all hosts in the inventory file are in the same environment
    environment: "test"
    hosts:
    # env + name is a unique string across all inventory files
    # this will be used in the input/default.yaml file to reference the host
    - name: "nram-poc"
      host: "aks-poc2"
      sempUrl: "https://nram-poc2.messaging.solace.cloud:943"
      sempUser: "aks-poc2-admin"
      #sempPassword: "secret" # read from env
      vpn: "aks-poc2"
      
    - name: "nram-dev"
      host: "sc-nram-dev1"
      sempUrl: "https://nram-dev1.messaging.solace.cloud:943"
      sempUser: "nram-dev1-admin"
      #sempPassword: "secret" # read from env
      vpn: "nram-dev1"

    - name: "nram-test"
      host: "sc-nram-test"
      sempUrl: "https://nram-test1.messaging.solace.cloud:943"
      sempUser: "nram-test-admin"
      #sempPassword: "secret" # read from env
      vpn: "nram-test"

    - name: "nram-dev2"
      host: "sc-nram-dev2"
      sempUrl: "https://nram-dev2.messaging.solace.cloud:943"
      sempUser: "nram-ohio-vpn-admin"
      #sempPassword: "secret" # read from env
      vpn: "nram-ohio-vpn"
