# Solace router and access info for the application

---
inventory:
    # set SEMP_PASSWORD secret variable in the environment
    # env is not currently used. 
    environment: "cloud"
    hosts:
    # name is a unique string across all inventory files
    # host is used for logging and is not used for the sempUrl
    # name is used in the input/csv/queues.csv in the first column (vpnName)
    - name: "nram-prod1"
      host: "nram-gke-poc"
      sempUrl: "https://mr-connection-ipvocjircbz.messaging.solace.cloud:943"
      sempUser: "nram-prod1-admin"
      #sempPassword: "secret" # read from env
      vpn: "nram-prod1"