# Solace router and access info for the application

---
inventory:
    hosts:
    # environment matches the --env value used on the command line
    - environment: "nram-local"
      host: "localhost"
      sempUrl: "http://localhost:8080"
      sempUser: "admin"
      #sempPassword: "secret" # read from env
      vpn: "default"

    - environment: "nram-remote"
      host: "nram-latitude"
      sempUrl: "http://nram-latitude:8080"
      sempUser: "admin"
      #sempPassword: "secret" # read from env
      vpn: "default"