name: Post on Change

on:
  push:
    paths:
      - 'input/**'

jobs:
  solace_service_job:
    runs-on: ubuntu-latest
    # for NT
    #runs-on: [ self-hosted, enterprise, docker, Linux ]
    #container:
    #  image: ghcr.io/northerntrust-internal/ghe/python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install datetime logging requests pathlib pyyaml 

      - name: Run solace-service-manager.py
        run: |
          # required for NT
          #export http_proxy=$HTTP_PROXY
          #export https_proxy=$HTTPS_PROXY
          #echo "http_proxy set to $http_proxy"
          echo "Input file : $INPUT_FILE (${{ env.INPUT_FILE }})"
          python scripts/solace-service-manager.py --input $INPUT_FILE
        env:
          SEMP_USER: ${{ env.SEMP_USER }}
          SEMP_PASSWORD: ${{ secrets.SEMP_PASSWORD }}
          INPUT_FILE: ${{ env.INPUT_FILE }}          
          # NT
          #HTTP_PROXY: "http://199.16.205.1:9443/"
          #HTTPS_PROXY: "https://199.16.205.1:9443/"
