name: Post on Change

on:
  push:
    paths:
      - 'input/**'

jobs:
  solace_service_job:
    runs-on: ubuntu-latest
    # for NT
    #runs-on: [ self-hosted, enterprise, docker, Linux ]
    #container:
    #  image: ghcr.io/northerntrust-internal/ghe/python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install datetime logging requests pathlib pyyaml 
        
      - name: Extract branch name
        id: extract_branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

        # INPUT_FILE : input/<branch-name>.yaml (eg: input/nram-dev.yaml)
        # SEMP_PASSWORD : SEMP_PASSWORD_<branch>.yaml (Eg: SEMP_PASSWORD_NRAM_DEV)
      - name: Set up environment variables
        run: |
          echo "INPUT_FILE=input/$BRANCH_NAME.yaml" >> $GITHUB_ENV

      - name: Run solace-service-manager.py (${{ env.INPUT_FILE }})...
        run: |
          # required for NT
          #export http_proxy=$HTTP_PROXY
          #export https_proxy=$HTTPS_PROXY
          #echo "http_proxy set to $http_proxy"
          python scripts/solace-service-manager.py --input $INPUT_FILE
        env:
          #SEMP_USER: ${{ vars.SEMP_USER }}
          SEMP_PASSWORD: ${{ secrets.SEMP_PASSWORD }}
          #SEMP_PASSWORD: ${{ env.SEMP_PASSWORD }}
          INPUT_FILE: ${{ env.INPUT_FILE }}
          # NT
          #HTTP_PROXY: "http://199.16.205.1:9443/"
          #HTTPS_PROXY: "https://199.16.205.1:9443/"
