name: Post on Change

on:
  push:
    paths:
      - 'input/**'

jobs:
  solace_service_job:
    runs-on: ubuntu-latest
    # for NT
    #runs-on: [ self-hosted, enterprise, docker, Linux ]
    #container:
    #  image: ghcr.io/northerntrust-internal/ghe/python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install datetime logging requests pathlib pyyaml 
        
      - name: Extract branch name
        id: extract_branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

        # CSV_FILE : input/csv/queues.csv
        # SEMP_PASSWORD : SEMP_PASSWORD environment variable
      - name: Set up environment variables
        run: |
          echo "CSV_FILE_USERS=input/csv/client-usernames.csv" >> $GITHUB_ENV
          echo "CSV_FILE_ACL_PROFILE=input/csv/acl-profiles.csv" >> $GITHUB_ENV
          echo "CSV_FILE_CLIENT_PROFILE=input/csv/client-profiles.csv" >> $GITHUB_ENV

      - name: Run solace_self_service.sh (${{ env.CSV_FILE }})...
        run: |
          # required for NT
          #export http_proxy=$HTTP_PROXY
          #export https_proxy=$HTTPS_PROXY
          #echo "http_proxy set to $http_proxy"
          bash scripts/solace_self_service.sh --csv-file $CSV_FILE_ACL_PROFILE --verbose
          #disable for cloud
          #bash scripts/solace_self_service.sh --csv-file $CSV_FILE_CLIENT_PROFILE --verbose
          bash scripts/solace_self_service.sh --csv-file $CSV_FILE_CLIENT_USERS --verbose
        env:
          #SEMP_USER: ${{ vars.SEMP_USER }}
          SEMP_PASSWORD: ${{ secrets.SEMP_PASSWORD }}
          #SEMP_PASSWORD: ${{ env.SEMP_PASSWORD }}
          CSV_FILE: ${{ env.CSV_FILE }}
          # NT
          #HTTP_PROXY: "http://199.16.205.1:9443/"
          #HTTPS_PROXY: "https://199.16.205.1:9443/"
